[project]
name = "autoconda"
version = "0.3.0"
requires-python = ">=3.10"
dependencies = [
    "pyyaml",
]

[project.scripts]
autoconda = "autoconda.cli:main"

[dependency-groups]
dev = [
  "pytest",
]
